FROM microsoft/dotnet:2.1-sdk AS installer-env

COPY ./src/Arragro.ObjectHistory.AzureFunctions /src/dotnet-function-app
COPY ./src/Arragro.ObjectHistory.Core /src/Arragro.ObjectHistory.Core
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet:2.0

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]