version: '2.4'
services:
  mcr-azurite:
    restart: always
    image: mcr.microsoft.com/azure-storage/azurite:3.11.0
    ports:
      - 10000:10000
      - 10001:10001
    networks:
      - object-history-net
    #volumes:
    #  - mcr-azurite-data:/data

  azurite:
    restart: always
    image: touchify/azurite:2.7.1
    ports:
      - 10002:10002
    networks:
      - object-history-net
    #volumes:
    #  - azurite-data:/data
#    volumes:
#      - azurite-object-history-data:/opt/azurite/folder

  #object-history_service:
  #  image: deleteme:v1
  #  depends_on:
  #    - azurite
  #  networks:
  #    - object-history-net
  #  environment:
  #    - AzureWebJobsScriptRoot=/home/site/wwwroot
  #    - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
  #    - AzureWebJobsDashboard=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
networks:
  object-history-net:

#volumes:
#  mcr-azurite-data:
#  azurite-data: