// <auto-generated />
using System;
using Arragro.ObjectHistory.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arragro.ObjectHistory.EFCore.Migrations.Postgres
{
    [DbContext(typeof(ArragroObjectHistoryPGContext))]
    [Migration("20250602034015_SnakeCase")]
    partial class SnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("object_history")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arragro.ObjectHistory.EFCore.ObjectHistoryDeletedTableEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("partition_key");

                    b.Property<long>("RowKey")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("row_key");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("application_name");

                    b.Property<Guid>("Folder")
                        .HasColumnType("uuid")
                        .HasColumnName("folder");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("metadata");

                    b.Property<string>("SecurityValidationToken")
                        .HasColumnType("text")
                        .HasColumnName("security_validation_token");

                    b.Property<Guid?>("SubFolder")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_folder");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PartitionKey", "RowKey")
                        .HasName("pk_object_history_deleted_table_entities");

                    b.HasIndex("RowKey")
                        .HasDatabaseName("ix_object_history_deleted_table_entities_row_key");

                    b.ToTable("object_history_deleted_table_entities", "object_history");
                });

            modelBuilder.Entity("Arragro.ObjectHistory.EFCore.ObjectHistoryGlobalTableEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("partition_key");

                    b.Property<long>("RowKey")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("row_key");

                    b.Property<Guid>("Folder")
                        .HasColumnType("uuid")
                        .HasColumnName("folder");

                    b.Property<bool>("IsAdd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_add");

                    b.Property<string>("Metadata")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metadata");

                    b.Property<string>("ObjectName")
                        .HasColumnType("text")
                        .HasColumnName("object_name");

                    b.Property<string>("SecurityValidationToken")
                        .HasColumnType("text")
                        .HasColumnName("security_validation_token");

                    b.Property<Guid?>("SubFolder")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_folder");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PartitionKey", "RowKey")
                        .HasName("pk_object_history_global_table_entity");

                    b.HasIndex("RowKey")
                        .HasDatabaseName("ix_object_history_global_table_entity_row_key");

                    b.ToTable("object_history_global_table_entity", "object_history");
                });

            modelBuilder.Entity("Arragro.ObjectHistory.EFCore.ObjectHistoryTableEntity", b =>
                {
                    b.Property<string>("PartitionKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("partition_key");

                    b.Property<long>("RowKey")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("row_key");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("application_name");

                    b.Property<Guid>("Folder")
                        .HasColumnType("uuid")
                        .HasColumnName("folder");

                    b.Property<bool>("IsAdd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_add");

                    b.Property<string>("Metadata")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metadata");

                    b.Property<string>("SecurityValidationToken")
                        .HasColumnType("text")
                        .HasColumnName("security_validation_token");

                    b.Property<Guid?>("SubFolder")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_folder");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("User")
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PartitionKey", "RowKey")
                        .HasName("pk_object_history_table_entity");

                    b.HasIndex("RowKey")
                        .HasDatabaseName("ix_object_history_table_entity_row_key");

                    b.ToTable("object_history_table_entity", "object_history");
                });
#pragma warning restore 612, 618
        }
    }
}
